language: node_js
node_js:
  - "12"
  - "10"
  - "8"

before_install:
- |
  case "${TRAVIS_OS_NAME}" in
    "windows")
      # yarn isn't installed by default
      npm install --global yarn
    ;;
  esac

install: yarn

before_script:
  - yarn --version
