language: node_js

sudo: false

node_js:
  - "12"
  # - "10"
  # - "8"

cache:
  directories:
  - node_modules

before_install:
- |
  case "${TRAVIS_OS_NAME}" in
    "windows")
      # yarn isn't installed by default
      npm install --global yarn
    ;;
  esac

install: yarn

before_script:
  - yarn --version

script:
- npm test
- npm run coveralls
